trigger: none
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Talend Variables
- name: project_name
  value: 'P_AZURETMC'

- name: talend_ci_config
  value: >-
    -DforceUpdate=true
    -Dlicense.path=$(license.secureFilePath)
    -Dtalend.studio.p2.base=$(p2_base_url)
    -Dtalend.studio.p2.update=$(p2_update_url)
    -Pcloud-publisher
    -Dservice.url=$(CLOUD_URL)
    -Dcloud.token=$(CLOUD_TOKEN)          
    -Dcloud.publisher.screenshot=true 
    -Dcloud.publisher.environment=DEV
    -Dcloud.publisher.workspace=Cloud_Run

steps:
  - task: DownloadSecureFile@1
    name: settings_xml
    inputs:
      secureFile: settings.xml

  - task: DownloadSecureFile@1
    name: license
    inputs:
      secureFile: license

  - task: DownloadSecureFile@1
    name: pom_xml
    inputs:
      secureFile: sample_pom.xml

  - task: DownloadSecureFile@1
    name: cibuilder
    inputs:
      secureFile: Talend-CI-Builder-Maven-Plugin-20211109_1610-V8.0.1.zip

  - task: ExtractFiles@1
    displayName: Extract files
    inputs:
      archiveFilePatterns: '$(cibuilder.secureFilePath)'
      destinationFolder: '/home/vsts/work/_temp/builder/'
      cleanDestinationFolder: true 
      overwriteExistingFiles: true

  - task: Maven@3
    displayName: 'Maven install builder plugin'
    inputs:
      mavenPomFile: '$(pom_xml.secureFilePath)'
      goals: 'install:install-file' 
      options: '--batch-mode --settings $(settings_xml.secureFilePath) '
      mavenOptions: |
        -Dfile=./builder/Talend-CI-Builder-Maven-Plugin-20211109_1610-V8.0.1/builder-maven-plugin-8.0.1.jar
        -DpomFile=./builder/Talend-CI-Builder-Maven-Plugin-20211109_1610-V8.0.1/builder-maven-plugin-8.0.1.pom
  
  - task: Maven@3
    displayName: 'Maven install P2 and generate POMs'
    inputs:
      mavenPomFile: '$(pom_xml.secureFilePath)'
      goals: 'org.talend.ci:builder-maven-plugin:8.0.1:generateAllPoms' 
      options: '--batch-mode --settings $(settings_xml.secureFilePath) $(talend_ci_config)'
      publishJUnitResults: false

  - task: CmdLine@2
    displayName: 'List modules / available artifacts to build'
    inputs:
      script: |
        pwd
        cat $(project_name)/poms/pom.xml | sed '/<modules>/,/<\/modules>/!d'

  - task: Maven@3
    displayName: 'Maven build & publish Talend artifacts to Talend Cloud'
    inputs:
        mavenPomFile: '$(project_name)/poms/pom.xml'
        goals: 'deploy' #compile / deploy
        options: '--batch-mode --settings $(settings_xml.secureFilePath) -pl $(jobs_to_build) -am -fae $(talend_ci_config)'
